--PUNTO 6

SELECT REGEXP_SUBSTR(NOMBRE,'[^ ]+') FROM USUARIO ORDER BY USUARIO.NOMBRE ASC;

--PUNTO 7 (ya que no existen en nuestra tienda juegos por un valor tan alto de 300k usaremos juegos valuados en 30k)

SELECT DISTINCT NOMBRE FROM USUARIO INNER JOIN CONSUME ON (USUARIO.IDUSUARIO = CONSUME.IDUSUARIO)
INNER JOIN TRANSACCIONES ON (TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION)
WHERE 
TRANSACCIONES.PRECIO > 30000 AND 2021 = EXTRACT(YEAR FROM TRANSACCIONES.FECHA);

--PUNTO 10 *SE SIGUE ESPERANDO*

SELECT USUARIO.IDUSUARIO, USUARIO.NOMBRE, TRANSACCIONES.FECHA, TRANSACCIONES.PRECIO
FROM CONSUME INNER JOIN TRANSACCIONES ON (TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION)RIGHT OUTER JOIN USUARIO
WHERE EXTRACT(MONTH FROM TRANSACCIONES.FECHA) = EXTRACT(MONTH FROM CURRENT_DATE); 