--PUNTO 6

SELECT REGEXP_SUBSTR(NOMBRE,'[^ ]+') FROM USUARIO ORDER BY USUARIO.NOMBRE ASC;

--PUNTO 7 (ya que no existen en nuestra tienda juegos por un valor tan alto de 300k usaremos juegos valuados en 30k)

SELECT DISTINCT NOMBRE FROM USUARIO INNER JOIN CONSUME ON (USUARIO.IDUSUARIO = CONSUME.IDUSUARIO)
INNER JOIN TRANSACCIONES ON (TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION)
WHERE 
TRANSACCIONES.PRECIO > 30000 AND 2021 = EXTRACT(YEAR FROM TRANSACCIONES.FECHA);

--PUNTO 10 

SELECT USUARIO.IDUSUARIO, USUARIO.NOMBRE, TRANSACCIONES.FECHA, TRANSACCIONES.PRECIO
FROM USUARIO LEFT OUTER JOIN (CONSUME INNER JOIN TRANSACCIONES ON(TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION)) ON(usuario.idusuario = consume.idusuario)
WHERE EXTRACT(MONTH FROM TRANSACCIONES.FECHA) = EXTRACT(MONTH FROM CURRENT_DATE)
UNION
SELECT USUARIO.IDUSUARIO, USUARIO.NOMBRE, TRANSACCIONES.FECHA, TRANSACCIONES.PRECIO
FROM USUARIO LEFT OUTER JOIN (CONSUME INNER JOIN TRANSACCIONES ON(TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION)) ON(usuario.idusuario = consume.idusuario)
WHERE EXTRACT(MONTH FROM TRANSACCIONES.FECHA) IS NULL;

WITH pene AS (SELECT USUARIO.IDUSUARIO AS p1, USUARIO.NOMBRE AS p2, TRANSACCIONES.FECHA AS p3, TRANSACCIONES.PRECIO AS p4
FROM USUARIO LEFT OUTER JOIN (CONSUME INNER JOIN TRANSACCIONES ON(TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION)) ON(usuario.idusuario = consume.idusuario))
SELECT p1, p2, p3, p4
FROM pene
WHERE EXTRACT(MONTH FROM p3) = EXTRACT(MONTH FROM CURRENT_DATE)
UNION
SELECT p1, p2, p3, p4
FROM pene
WHERE EXTRACT(MONTH FROM p3) IS NULL;

SELE

SELECT DISTINCT USUARIO.IDUSUARIO, USUARIO.NOMBRE, TRANSACCIONES.FECHA, TRANSACCIONES.PRECIO
FROM USUARIO LEFT OUTER JOIN (CONSUME INNER JOIN TRANSACCIONES ON(TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION))
ON EXTRACT(MONTH FROM TRANSACCIONES.FECHA) = EXTRACT(MONTH FROM CURRENT_DATE);

