--PUNTO 6

SELECT REGEXP_SUBSTR(NOMBRE,'[^ ]+') FROM USUARIO ORDER BY USUARIO.NOMBRE ASC;

--PUNTO 7 (ya que no existen en nuestra tienda juegos por un valor tan alto de 300k usaremos juegos valuados en 30k)

SELECT DISTINCT NOMBRE FROM USUARIO INNER JOIN CONSUME ON (USUARIO.IDUSUARIO = CONSUME.IDUSUARIO)
INNER JOIN TRANSACCIONES ON (TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION)
WHERE 
TRANSACCIONES.PRECIO > 30000 AND 2021 = EXTRACT(YEAR FROM TRANSACCIONES.FECHA);

--PUNTO 10 

SELECT DISTINCT USUARIO.IDUSUARIO, USUARIO.NOMBRE, TRANSACCIONES.FECHA, TRANSACCIONES.PRECIO
FROM USUARIO LEFT OUTER JOIN (CONSUME INNER JOIN TRANSACCIONES 
ON (TRANSACCIONES.IDTRANSACCION = CONSUME.IDTRANSACCION 
and EXTRACT(MONTH FROM TRANSACCIONES.FECHA) = EXTRACT(MONTH FROM CURRENT_DATE))) 
ON (USUARIO.IDUSUARIO = CONSUME.IDUSUARIO);

